# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e3cd62a96fb0bbbf2d10ead1157af5aabbc358504c85c78b468d2a7cf0409d82911304d391d22692ec27edd1b9e47185545760afdf9ae08fc7940434e02c4ee6

test:
  secret_key_base: 6706b37c68ba9eb10db9e84fd3554e127660b6f61dfd03ee640e7ec2b23a350378e7d8853432002c120d55d7f6555c841c67096c85a15c66dede007bb2d3fb26

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
